In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')
print(df.shape)
df.head()

(1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df,df['SalePrice'],test_size = 0.2,random_state = 0)

# Missing Values

In [4]:
# Missing Values in categorical variable
feature_with_nan = [feature for feature in df.columns if df[feature].isnull().sum() > 1 and df[feature].dtype =='O']

for feature in feature_with_nan:
    print('{} : {}% missing values'.format(feature,np.around(df[feature].isnull().mean(),4)))

Alley : 0.9377% missing values
MasVnrType : 0.0055% missing values
BsmtQual : 0.0253% missing values
BsmtCond : 0.0253% missing values
BsmtExposure : 0.026% missing values
BsmtFinType1 : 0.0253% missing values
BsmtFinType2 : 0.026% missing values
FireplaceQu : 0.4726% missing values
GarageType : 0.0555% missing values
GarageFinish : 0.0555% missing values
GarageQual : 0.0555% missing values
GarageCond : 0.0555% missing values
PoolQC : 0.9952% missing values
Fence : 0.8075% missing values
MiscFeature : 0.963% missing values

In [5]:
# Replace missing values with new values
def replace_cat_feature(df,feature_nan):
    data = df.copy()
    data[feature_nan] = data[feature_nan].fillna('Missing')
    return data

df = replace_cat_feature(df,feature_with_nan)
df[feature_with_nan].isnull().sum()

Alley           0
MasVnrType      0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
PoolQC          0
Fence           0
MiscFeature     0
dtype: int64

In [6]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,...,0,Missing,Missing,Missing,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,...,0,Missing,Missing,Missing,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,12,2008,WD,Normal,250000

In [7]:
numerical_with_nan = [feature for feature in df.columns if df[feature].isnull().sum() > 1 and df[feature].dtypes != 'O']
for feature in numerical_with_nan:
    print('{} : {}% missing values'.format(feature,np.around(df[feature].isnull().mean(),4)))

LotFrontage : 0.1774% missing values
MasVnrArea : 0.0055% missing values
GarageYrBlt : 0.0555% missing values

In [8]:
for feature in numerical_with_nan:
    median = df[feature].median()
    
    df[feature+'nan'] = np.where(df[feature].isnull(),1,0)
    df[feature].fillna(median,inplace = True)

df[numerical_with_nan].isnull().sum()

LotFrontage    0
MasVnrArea     0
GarageYrBlt    0
dtype: int64

In [9]:
df.head(50)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,250000,0,0,0
5,6,50,RL,85.0,14115,Pave,Missing,IR1,Lvl,AllPub,...,Shed,700,10,2009,WD,Normal,143000,0,0,0
6,7,20,RL,75.0,10084,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,8,2007,WD,Normal,307000,0,0,0
7,8,60,RL,69.0,10382,Pave,Missing,IR1,Lvl,AllPub,...,Shed,350,11,2009,WD,Normal,200000,1,0,0
8,9,50,RM,51.0,6120,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,4,2008,WD,Abnorml,129900,0,0,0
9,10,190,RL,50.0,7420,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,1,2008,WD,Normal,118000,0,0,0
10,11,20,RL,70.0,11200,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,129500,0,0,0
11,12,60,RL,85.0,11924,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,7,2006,New,Partial,345000,0,0,0
12,13,20,RL,69.0,12968,Pave,Missing,IR2,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,144000,1,0,0
13,14,20,RL,91.0,10652,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,8,2007,New,Partial,279500,0,0,0
14,15,20,RL,69.0,10920,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,5,2008,WD,Normal,157000,1,0,0
15,16,45,RM,51.0,6120,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,7,2007,WD,Normal,132000,0,0,0
16,17,20,RL,69.0,11241,Pave,Missing,IR1,Lvl,AllPub,...,Shed,700,3,2010,WD,Normal,149000,1,0,0
17,18,90,RL,72.0,10791,Pave,Missing,Reg,Lvl,AllPub,...,Shed,500,10,2006,WD,Normal,90000,0,0,0
18,19,20,RL,66.0,13695,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,6,2008,WD,Normal,159000,0,0,0
19,20,20,RL,70.0,7560,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2009,COD,Abnorml,139000,0,0,0
20,21,60,RL,101.0,14215,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,11,2006,New,Partial,325300,0,0,0
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,Missing,0,6,2007,WD,Normal,139400,0,0,0
22,23,20,RL,75.0,9742,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,230000,0,0,0
23,24,120,RM,44.0,4224,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,6,2007,WD,Normal,129900,0,0,0
24,25,20,RL,69.0,8246,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,5,2010,WD,Normal,154000,1,0,0
25,26,20,RL,110.0,14230,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,7,2009,WD,Normal,256300,0,0,0
26,27,20,RL,60.0,7200,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2010,WD,Normal,134800,0,0,0
27,28,20,RL,98.0,11478,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2010,WD,Normal,306000,0,0,0
28,29,20,RL,47.0,16321,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2006,WD,Normal,207500,0,0,0
29,30,30,RM,60.0,6324,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,5,2008,WD,Normal,68500,0,0,0
30,31,70,C (all),50.0,8500,Pave,Pave,Reg,Lvl,AllPub,...,Missing,0,7,2008,WD,Normal,40000,0,0,0
31,32,20,RL,69.0,8544,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,6,2008,WD,Normal,149350,1,0,0
32,33,20,RL,85.0,11049,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,1,2008,WD,Normal,179900,0,0,0
33,34,20,RL,70.0,10552,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,4,2010,WD,Normal,165500,0,0,0
34,35,120,RL,60.0,7313,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,8,2007,WD,Normal,277500,0,0,0
35,36,60,RL,108.0,13418,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,9,2006,WD,Normal,309000,0,0,0
36,37,20,RL,112.0,10859,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,6,2009,WD,Normal,145000,0,0,0
37,38,20,RL,74.0,8532,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,10,2009,WD,Normal,153000,0,0,0
38,39,20,RL,68.0,7922,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,1,2010,WD,Abnorml,109000,0,0,0
39,40,90,RL,65.0,6040,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,6,2008,WD,AdjLand,82000,0,0,1
40,41,20,RL,84.0,8658,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,12,2006,WD,Abnorml,160000,0,0,0
41,42,20,RL,115.0,16905,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,7,2007,WD,Normal,170000,0,0,0
42,43,85,RL,69.0,9180,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2007,WD,Normal,144000,1,0,0
43,44,20,RL,69.0,9200,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,7,2008,WD,Normal,130250,1,0,0
44,45,20,RL,70.0,7945,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2006,WD,Normal,141000,0,0,0
45,46,120,RL,61.0,7658,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2010,WD,Normal,319900,0,0,0
46,47,50,RL,48.0,12822,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,8,2009,WD,Abnorml,239686,0,0,0
47,48,20,FV,84.0,11096,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,7,2007,WD,Normal,249700,0,0,0
48,49,190,RM,33.0,4456,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,6,2009,New,Partial,113000,0,0,1
49,50,20,RL,66.0,7742,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,1,2007,WD,Normal,127000,0,0,0

In [10]:
# Temporal Variable 
for feature in ['YearBuilt','YearRemodAdd','GarageYrBlt']:
    df[feature] = df['YrSold'] - df[feature]

In [11]:
df[['YearBuilt','YearRemodAdd','GarageYrBlt']].head()

   YearBuilt  YearRemodAdd  GarageYrBlt
0          5             5          5.0
1         31            31         31.0
2          7             6          7.0
3         91            36          8.0
4          8             8          8.0

#  Numerical Variables
since the numerical features are skewed we will perform log normal distribution

In [12]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,250000,0,0,0

In [13]:
num_feature = ['LotFrontage','LotArea','1stFlrSF','GrLivArea','SalePrice']

for feature in num_feature:
    df[feature] = np.log(df[feature])

In [14]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,4.174387,9.041922,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,12.247694,0,0,0
1,2,20,RL,4.382027,9.169518,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,12.109011,0,0,0
2,3,60,RL,4.219508,9.328123,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,12.317167,0,0,0
3,4,70,RL,4.094345,9.164296,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,11.849398,0,0,0
4,5,60,RL,4.430817,9.565214,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,12.429216,0,0,0

# Handeling rare categorical feature
remove categorical that are present less then 1% of the observation

In [15]:
cat_feature = [feature for feature in df.columns if df[feature].dtypes == 'O']

In [16]:
cat_feature

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [17]:
for feature in cat_feature:
    temp = df.groupby(feature)['SalePrice'].count()/len(df)
    temp_df = temp[temp > 0.01].index
    df[feature] = np.where(df[feature].isin(temp_df),df[feature],'Rare_Var')

In [19]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,4.174387,9.041922,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,12.247694,0,0,0
1,2,20,RL,4.382027,9.169518,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,12.109011,0,0,0
2,3,60,RL,4.219508,9.328123,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,12.317167,0,0,0
3,4,70,RL,4.094345,9.164296,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,11.849398,0,0,0
4,5,60,RL,4.430817,9.565214,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,12.429216,0,0,0

In [27]:
for feature in cat_feature:
    labels_ordered=df.groupby([feature])['SalePrice'].mean().sort_values().index
    labels_ordered={k:i for i,k in enumerate(labels_ordered,0)}
    df[feature]=df[feature].map(labels_ordered)

In [28]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,3,4.174387,9.041922,1,2,0,1,1,...,2,0,2,2008,2,3,12.247694,0,0,0
1,2,20,3,4.382027,9.169518,1,2,0,1,1,...,2,0,5,2007,2,3,12.109011,0,0,0
2,3,60,3,4.219508,9.328123,1,2,1,1,1,...,2,0,9,2008,2,3,12.317167,0,0,0
3,4,70,3,4.094345,9.164296,1,2,1,1,1,...,2,0,2,2006,2,0,11.849398,0,0,0
4,5,60,3,4.430817,9.565214,1,2,1,1,1,...,2,0,12,2008,2,3,12.429216,0,0,0

## Feature Scaling

In [29]:
feature_scale = [feature for feature in df.columns if feature not in  ['Id','SalePrice']]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(df[feature_scale])

MinMaxScaler()

In [30]:
scaler.transform(df[feature_scale])

array([[0.23529412, 0.75      , 0.41820812, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.49506375, ..., 0.        , 0.        ,
        0.        ],
       [0.23529412, 0.75      , 0.434909  , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.29411765, 0.75      , 0.42385922, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.434909  , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.75      , 0.47117546, ..., 0.        , 0.        ,
        0.        ]])

In [32]:
# transform the train and test set, and add on the Id and SalePrice variables
data = pd.concat([df[['Id', 'SalePrice']].reset_index(drop=True),
                    pd.DataFrame(scaler.transform(df[feature_scale]), columns=feature_scale)],
                    axis=1)

In [33]:
data.head()

,Id,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,12.247694,0.235294,0.75,0.418208,0.366344,1.0,1.0,0.000000,0.333333,...,1.0,1.0,0.0,0.090909,0.50,0.666667,0.75,0.0,0.0,0.0
1,2,12.109011,0.000000,0.75,0.495064,0.391317,1.0,1.0,0.000000,0.333333,...,1.0,1.0,0.0,0.363636,0.25,0.666667,0.75,0.0,0.0,0.0
2,3,12.317167,0.235294,0.75,0.434909,0.422359,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,0.727273,0.50,0.666667,0.75,0.0,0.0,0.0
3,4,11.849398,0.294118,0.75,0.388581,0.390295,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,0.090909,0.00,0.666667,0.00,0.0,0.0,0.0
4,5,12.429216,0.235294,0.75,0.513123,0.468761,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,1.000000,0.50,0.666667,0.75,0.0,0.0,0.0

In [34]:
data.to_csv('X_train.csv',index=False)